(function(){
'use strict';const $=s=>document.querySelector(s),D=Drafting,S=DocumentStore;
const dialog=document.createElement('dialog');dialog.innerHTML='<form id="annexForm"><h2>Ajouter une annexe</h2><label>Titre<input id="annexTitle" required></label><label>Fichier PDF<input id="annexFile" type="file" accept="application/pdf,.pdf" required></label><label><input id="annexBefore" type="checkbox" checked> Inclure dans le dossier avant conseil</label><label><input id="annexAfter" type="checkbox" checked> Inclure dans le dossier définitif</label><p id="annexError" role="alert"></p><button type="button" id="cancelAnnex" class="ghost-btn">Annuler</button> <button id="submitAnnex" class="primary-inline">Téléverser et rattacher</button></form>';document.body.append(dialog);let busy=false;
$('#cancelAnnex').onclick=()=>{if(!busy)dialog.close();};dialog.addEventListener('cancel',e=>{if(busy)e.preventDefault();});
$('#addAnnex').onclick=()=>{const c=D.context();if(!c.id||c.dirty){alert('Enregistrez d’abord le projet et ses modifications.');return;}if(!c.access||D.readOnly())return;$('#annexForm').reset();$('#annexError').textContent='';dialog.showModal();};
$('#annexForm').onsubmit=async e=>{e.preventDefault();if(busy)return;busy=true;$('#submitAnnex').disabled=true;$('#cancelAnnex').disabled=true;let committed=false;try{
 const c=D.context(),file=$('#annexFile').files[0],title=$('#annexTitle').value.trim();if(!title)throw Error('Renseignez un titre.');if(!c.access||c.dirty||D.readOnly())throw Error('Le projet doit être enregistré et modifiable.');
 await S.validatePdf(file);await S.ensure(grist.docApi,'ANNEXES',[{id:'Fichier',type:'Attachments'}]);const before=await D.fetchDB();if(DraftingData.locked(before,c.id))throw Error('Le projet a été verrouillé.');
 const baseline=S.fingerprint(DraftingData.scope(before,c.id));const aid=await S.upload(grist.docApi,file);const fresh=await D.fetchDB();
 if(!D.context().access||D.context().id!==c.id||D.context().dirty||DraftingData.locked(fresh,c.id)||S.fingerprint(DraftingData.scope(fresh,c.id))!==baseline)throw Error('Le projet a changé pendant le téléversement. Le fichier n’a pas été rattaché. Actualisez.');
 await grist.docApi.applyUserActions([['AddRecord','ANNEXES',null,{Deliberation:c.id,Ordre_annexe:Math.max(0,...fresh.ANNEXES.filter(a=>a.Deliberation===c.id).map(a=>a.Ordre_annexe||0))+1,Titre_annexe:title,Fichier:['L',aid],Obligatoire_dossier_preparatoire:$('#annexBefore').checked,Obligatoire_acte_definitif:$('#annexAfter').checked,Mention_dans_deliberation:false}],['AddRecord','JOURNAL_ACTIONS',null,{Deliberation:c.id,Seance:before.DELIBERATIONS.find(d=>d.id===c.id)?.Seance||0,Date_action:Date.now()/1000,Description:'Ajout de l’annexe : '+title,Type_action:'Autre',Niveau:'Information'}]]);committed=true;dialog.close();await D.refresh();
 }catch(e){$('#annexError').textContent=(committed?'Annexe enregistrée. Actualisez avant de poursuivre. ':'')+e.message;}finally{busy=false;$('#submitAnnex').disabled=false;$('#cancelAnnex').disabled=false;}};
})();
