(function(){
'use strict';const $=s=>document.querySelector(s),S=DocumentStore,esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));let db=null,sid=0,busy=false,access=false,urls=[];
const tables=[...CouncilExports.tables,'JOURNAL_ACTIONS'];
const status=(t,error=false)=>{$('#archiveMessage').textContent=t;$('#archiveMessage').className='connection-status '+(error?'error':'connected');};
function clear(){urls.forEach(URL.revokeObjectURL);urls=[];$('#finalDownloads').replaceChildren();}
function controls(){$('#archiveMain').inert=!access||busy||!db;}
const dirty=()=>[...document.querySelectorAll('[data-number]')].some(e=>e.value!==(db.DELIBERATIONS.find(d=>d.id===Number(e.dataset.number))?.Numero_deliberation||''));
async function fetchDB(){const values=await Promise.all(tables.map(t=>grist.docApi.fetchTable(t)));if(!access)throw Error('Accès complet requis.');return Object.fromEntries(values.map((v,i)=>[tables[i],S.rows(v)]));}
async function run(fn){if(busy)return;busy=true;controls();try{await fn();}catch(e){status(e.message,true);}finally{busy=false;controls();}}
function links(did){return db.DOCUMENTS_GENERES.filter(r=>r.Seance===sid&&(r.Deliberation||0)===did&&r.Type_document===(did?'Délibération signée':'Convocation signée')).sort((a,b)=>(b.Version||0)-(a.Version||0)||b.id-a.id).map(r=>`<p>${r.Empreinte_source===S.source(db,sid,did)?'Signé archivé':'Version archivée — les données ont changé'} · version ${r.Version||1}${r.Date_archivage?' · '+esc(new Date(r.Date_archivage*1000).toLocaleString('fr-FR',{timeZone:'Europe/Paris'})):''} <button class="ghost-btn" data-download="${r.id}">${esc(r.Nom_original||'Télécharger le PDF')}</button></p>`).join('')||'<p>Aucun exemplaire signé archivé.</p>';}
function render(){
 clear();const councils=db.SEANCES_CM.filter(S.closed).sort((a,b)=>b.Date_heure_seance-a.Date_heure_seance);if(!councils.some(s=>s.id===sid))sid=councils[0]?.id||0;
 $('#closedCouncil').innerHTML=councils.length?councils.map(s=>`<option value="${s.id}" ${sid===s.id?'selected':''}>${esc(s.Libelle_seance||s.Reference_seance)}</option>`).join(''):'<option>Aucun conseil terminé</option>';
 $('#closedContent').hidden=!sid;$('#reopenCouncil').hidden=!sid;if(!sid){$('#closedSummary').textContent='Terminez le conseil depuis Suivi de séance pour le retrouver ici.';return;}
 const points=db.ORDRE_DU_JOUR.filter(p=>p.Seance===sid).sort((a,b)=>a.Ordre_point-b.Ordre_point||a.id-b.id);$('#closedSummary').textContent=points.length+' point(s) — consultation des résultats validés et archivage des signatures.';$('#signedLetters').innerHTML=links(0);
 $('#finalRecords').innerHTML=points.map(p=>{const d=db.DELIBERATIONS.find(d=>d.id===p.Deliberation);if(!d)return `<article class="archive-record"><strong>${esc(p.Intitule_point)}</strong><p>Point d’information — ${esc(p.Statut_suivi)}</p></article>`;const eligible=['Adoptée','Rejetée'].includes(d.Decision_seance);let label=d.Decision_seance||'Résultat absent';if(eligible){try{const o=FinalModel.result(db,d);label=o.label+` — ${o.t.for} pour, ${o.t.against} contre, ${o.t.abstain} abstention(s), ${o.t.nppv} NPPV`;}catch(e){label=e.message;}}
 return `<article class="archive-record"><h3>${esc(p.Ordre_point+'. '+d.Objet)}</h3><p>${esc(label)}</p>${eligible?`<div class="archive-tools"><label>Numéro officiel<input data-number="${d.id}" value="${esc(d.Numero_deliberation||'')}" placeholder="Ex. 2026-71"></label><button data-save-number="${d.id}" class="secondary-btn">Enregistrer le numéro</button><button data-export="${d.id}" class="primary-inline">Exporter cette délibération</button></div><h4>Exemplaire signé et scanné</h4>${links(d.id)}<div class="archive-tools"><label>PDF signé<input type="file" accept="application/pdf,.pdf" data-scan="${d.id}"></label><button class="secondary-btn" data-upload="${d.id}">Archiver le PDF signé</button></div>`:''}</article>`;}).join('');
}
async function reload(){db=await fetchDB();render();status('Conseils terminés chargés.');}
function download(file){const url=URL.createObjectURL(file.blob);urls.push(url);const a=document.createElement('a');a.href=url;a.download=file.name;a.textContent=file.name;a.className='secondary-btn';$('#finalDownloads').append(a);}
async function generate(did=0){if(dirty())throw Error('Enregistrez les numéros officiels avant de générer.');clear();status('Préparation des documents définitifs…');const fresh=await fetchDB();if(S.fingerprint(fresh)!==S.fingerprint(db))throw Error('Les données ont changé. Cliquez sur Actualiser.');const out=await CouncilExports.generate(fresh,sid,{api:grist.docApi,kind:did?'final':'finalComplete',deliberation:did,bw:$('#finalColor').value==='bw',pdf:$('#finalPdf').checked,word:$('#finalWord').checked});const after=await fetchDB();if(S.fingerprint(after)!==S.fingerprint(fresh))throw Error('Les données ont changé pendant la génération. Actualisez et recommencez.');out.files.forEach(download);status('Documents définitifs prêts à télécharger et à faire signer.');}
$('#finalDossier').onclick=()=>run(()=>generate());
$('#closedCouncil').onchange=()=>{if(dirty()&&!confirm('Abandonner les numéros non enregistrés ?')){$('#closedCouncil').value=String(sid);return;}sid=Number($('#closedCouncil').value);render();};
$('#reloadArchive').onclick=()=>{if(!dirty()||confirm('Abandonner les numéros non enregistrés ?'))run(reload);};
$('#reopenCouncil').onclick=()=>{if(dirty()||!confirm('Rouvrir ce conseil pour corriger les résultats ? Les fichiers signés resteront archivés. Après correction, générez de nouveaux actes et faites-les signer à nouveau.'))return;run(async()=>{const fresh=await fetchDB();if(S.fingerprint(fresh)!==S.fingerprint(db))throw Error('Actualisez avant de rouvrir.');if(fresh.SEANCES_CM.some(s=>s.id!==sid&&s.Statut_seance==='En cours'))throw Error('Un autre conseil est en cours : terminez-le avant cette correction.');await grist.docApi.applyUserActions([['UpdateRecord','SEANCES_CM',sid,{Statut_seance:'En cours'}],['AddRecord','JOURNAL_ACTIONS',null,{Seance:sid,Date_action:Date.now()/1000,Description:'Réouverture du conseil pour correction',Type_action:'Autre',Niveau:'Information'}]]);await reload();status('Conseil rouvert. Retrouvez-le dans Suivi de séance.');});};
$('#archiveMain').onclick=e=>{const b=e.target.closest('button');if(!b||b.disabled)return;
 if(b.dataset.export)run(()=>generate(Number(b.dataset.export)));
 if(b.dataset.saveNumber)run(async()=>{const did=Number(b.dataset.saveNumber),n=$(`[data-number="${did}"]`).value.trim();if(!n||n.length>60)throw Error('Renseignez un numéro officiel de 1 à 60 caractères.');const fresh=await fetchDB();if(!S.closed(fresh.SEANCES_CM.find(s=>s.id===sid)))throw Error('Le conseil a été rouvert.');if(S.fingerprint(fresh)!==S.fingerprint(db))throw Error('Les données ont changé. Actualisez.');if(fresh.DELIBERATIONS.some(d=>d.id!==did&&String(d.Numero_deliberation||'').trim().toLowerCase()===n.toLowerCase()))throw Error('Ce numéro officiel est déjà utilisé.');await S.ensure(grist.docApi,'DELIBERATIONS',[{id:'Numero_deliberation',type:'Text'}]);if(!access)throw Error('Accès retiré.');await grist.docApi.applyUserActions([['UpdateRecord','DELIBERATIONS',did,{Numero_deliberation:n}],['AddRecord','JOURNAL_ACTIONS',null,{Seance:sid,Deliberation:did,Date_action:Date.now()/1000,Description:'Numéro officiel enregistré : '+n,Type_action:'Autre',Niveau:'Information'}]]);const numberInputs=[...document.querySelectorAll('[data-number]')].filter(x=>Number(x.dataset.number)!==did).map(x=>[x.dataset.number,x.value]);await reload();numberInputs.forEach(([id,value])=>{const input=$(`[data-number="${id}"]`);if(input)input.value=value;});status('Numéro officiel enregistré.');});
 if(b.dataset.upload)run(async()=>{if(dirty())throw Error('Enregistrez les numéros avant de téléverser.');const did=Number(b.dataset.upload),d=db.DELIBERATIONS.find(d=>d.id===did);if(!d.Numero_deliberation)throw Error('Renseignez d’abord le numéro officiel.');const check=()=>{if(!access)throw Error('Accès retiré.');};await S.archive(grist.docApi,db,sid,did,$(`[data-scan="${did}"]`).files[0],fetchDB,check);await reload();status('Exemplaire signé archivé. Les anciennes versions sont conservées.');});
 if(b.dataset.download)run(async()=>{const doc=db.DOCUMENTS_GENERES.find(r=>r.id===Number(b.dataset.download));const bytes=await S.download(grist.docApi,S.ids(doc.Fichier)[0]);if(!access)throw Error('Accès retiré.');download({name:doc.Nom_original||'Document signé.pdf',blob:new Blob([bytes],{type:'application/pdf'})});});
};
['finalColor','finalPdf','finalWord'].forEach(id=>$('#'+id).onchange=clear);window.addEventListener('beforeunload',e=>{if(db&&dirty()){e.preventDefault();e.returnValue='';}});
if(!window.grist||parent===window){status('Installez archives.html dans un widget Grist avec accès complet.',true);return;}
grist.onOptions((o,i)=>{access=(i?.accessLevel??i?.access_level)==='full';if(!access){clear();status('Accès complet au document requis.',true);}controls();if(access&&!db)run(reload);});grist.ready({requiredAccess:'full'});
})();
