(function(root){
'use strict';
const rows=t=>(t.id||[]).map((id,i)=>Object.fromEntries(Object.keys(t).map(k=>[k,t[k][i]])));
const closed=s=>s?.Statut_seance==='Terminée';
const signedTypes={convocation:'Convocation signée',act:'Délibération signée'};
const ids=v=>Array.isArray(v)?v.filter(x=>Number.isInteger(x)&&x>0):[];
const canonical=v=>Array.isArray(v)?v.map(canonical):v&&typeof v==='object'?Object.fromEntries(Object.keys(v).sort().map(k=>[k,canonical(v[k])])):v;
const fingerprint=v=>JSON.stringify(canonical(v));
function source(db,sid,did=0){
 const s=db.SEANCES_CM.find(s=>s.id===sid),points=(db.ORDRE_DU_JOUR||[]).filter(p=>p.Seance===sid).sort((a,b)=>a.Ordre_point-b.Ordre_point||a.id-b.id);
 if(!did)return fingerprint({date:s?.Date_heure_seance,place:s?.Lieu_seance,letter:s?.Date_convocation,agenda:points.map(p=>({order:p.Ordre_point,title:p.Intitule_point||db.DELIBERATIONS.find(d=>d.id===p.Deliberation)?.Objet,deliberation:p.Deliberation}))});
 const articles=(db.ARTICLES||[]).filter(a=>a.Deliberation===did),aids=new Set(articles.map(a=>a.id)),tables=(db.TABLEAUX||[]).filter(t=>aids.has(t.Article)),tids=new Set(tables.map(t=>t.id)),ls=(db.LIGNES_TABLEAUX||[]).filter(l=>tids.has(l.Tableau)),lids=new Set(ls.map(l=>l.id));
 return fingerprint({session:{date:s?.Date_heure_seance,place:s?.Lieu_seance,president:s?.President_seance,secretary:s?.Secretaire_seance},point:points.filter(p=>p.Deliberation===did),deliberation:db.DELIBERATIONS.find(d=>d.id===did),articles,tables,lines:ls,columns:(db.COLONNES_TABLEAUX||[]).filter(c=>tids.has(c.Tableau)),cells:(db.CELLULES_TABLEAUX||[]).filter(c=>lids.has(c.Ligne)),...Object.fromEntries(['EXPOSE_MOTIFS','VISAS','CONSIDERANTS','ANNEXES','VOTES_DELIBERATIONS','AMENDEMENTS_SEANCE'].map(t=>[t,(db[t]||[]).filter(r=>r.Deliberation===did)]))});
}
function latest(db,sid,did=0){return (db.DOCUMENTS_GENERES||[]).filter(r=>r.Seance===sid&&(r.Deliberation||0)===did&&r.Type_document===signedTypes[did?'act':'convocation']).sort((a,b)=>(b.Version||0)-(a.Version||0)||b.id-a.id)[0];}
async function request(api,path,init={},readOnly=true){const token=await api.getAccessToken({readOnly});const url=token.baseUrl+path+(path.includes('?')?'&':'?')+'auth='+encodeURIComponent(token.token);let response;try{response=await fetch(url,{...init,credentials:'omit'});}catch(e){throw Error('Impossible de joindre le stockage Grist. Réessayez après avoir vérifié la connexion.');}if(!response.ok)throw Error('Grist a refusé l’accès au fichier (code '+response.status+').');return response;}
async function download(api,id){if(!Number.isInteger(id)||id<=0)throw Error('Référence de fichier invalide.');return new Uint8Array(await (await request(api,'/attachments/'+id+'/download')).arrayBuffer());}
async function validatePdf(file){if(!file||!file.size)throw Error('Choisissez un fichier PDF.');if(file.size>30*1024*1024)throw Error('Le fichier dépasse 30 Mo. Réduisez la taille du scan.');const bytes=new Uint8Array(await file.arrayBuffer());try{const pdf=await PDFLib.PDFDocument.load(bytes);if(!pdf.getPageCount())throw Error();}catch(e){throw Error('Le fichier doit être un PDF lisible, non chiffré et contenant au moins une page.');}return bytes;}
async function upload(api,file){await validatePdf(file);const body=new FormData();body.append('upload',file,file.name);const result=await (await request(api,'/attachments',{method:'POST',body},false)).json();if(!Array.isArray(result)||result.length!==1||!Number.isInteger(result[0]))throw Error('Réponse inattendue après téléversement. Vérifiez Grist avant de réessayer.');return result[0];}
async function ensure(api,table,columns){const ts=rows(await api.fetchTable('_grist_Tables')),cs=rows(await api.fetchTable('_grist_Tables_column')),t=ts.find(t=>t.tableId===table);if(!t)throw Error('Table manquante : '+table);const actions=[];for(const c of columns){const old=cs.find(x=>x.parentId===t.id&&x.colId===c.id);if(!old)actions.push(['AddColumn',table,c.id,{type:c.type,isFormula:false}]);else if(old.type!==c.type||(old.isFormula&&old.formula))throw Error('La colonne '+table+'.'+c.id+' doit être une colonne de données de type '+c.type+'.');}if(actions.length)await api.applyUserActions(actions);}
async function archive(api,db,sid,did,file,fresh,check=()=>{}){
 check();await validatePdf(file);await ensure(api,'DOCUMENTS_GENERES',[{id:'Empreinte_source',type:'Text'},{id:'Nom_original',type:'Text'},{id:'Date_archivage',type:'DateTime:Europe/Paris'},{id:'Fichier',type:'Attachments'}]);
 const stateOK=current=>{const session=current.SEANCES_CM.find(s=>s.id===sid);if(did){const d=current.DELIBERATIONS.find(d=>d.id===did),point=current.ORDRE_DU_JOUR.find(p=>p.Seance===sid&&p.Deliberation===did);if(!d||!point)throw Error('Délibération introuvable.');FinalModel.validate(current,session,[{d,point,title:d.Objet}]);}else if(!session?.Ordre_du_jour_valide)throw Error('Verrouillez l’ordre du jour avant d’archiver la convocation.');};
 const stamp=source(db,sid,did);const before=await fresh();check();stateOK(before);if(source(before,sid,did)!==stamp||fingerprint(latest(before,sid,did))!==fingerprint(latest(db,sid,did)))throw Error('Les données ont changé. Actualisez avant de téléverser.');
 const aid=await upload(api,file);const current=await fresh();check();stateOK(current);if(source(current,sid,did)!==stamp||fingerprint(latest(current,sid,did))!==fingerprint(latest(before,sid,did)))throw Error('Les données ont changé pendant le téléversement. Le fichier n’a pas été rattaché ; actualisez.');
 const version=(latest(current,sid,did)?.Version||0)+1;
 await api.applyUserActions([['AddRecord','DOCUMENTS_GENERES',null,{Seance:sid,Deliberation:did||0,Type_document:signedTypes[did?'act':'convocation'],Format_document:'PDF',Version:version,Statut_document:'Signé archivé',Fichier:['L',aid],Empreinte_source:stamp,Nom_original:file.name,Date_archivage:Date.now()/1000}],['AddRecord','JOURNAL_ACTIONS',null,{Seance:sid,Deliberation:did||0,Date_action:Date.now()/1000,Description:'Archivage de '+(did?'la délibération signée':'la convocation signée')+' — version '+version,Type_action:'Autre',Niveau:'Information'}]]);
}
root.DocumentStore={rows,closed,ids,source,latest,download,upload,ensure,archive,validatePdf,fingerprint};
})(typeof window==='undefined'?globalThis:window);
