(function(){
 'use strict';const P=PlanningData,$=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 let db,id=0,subjectId=0,baseline='',access=false,busy=false,needsReload=false;
 const rows=t=>(t.id||[]).map((id,i)=>Object.fromEntries(Object.keys(t).map(k=>[k,t[k][i]])));
 const dirty=()=>!!db&&$('#sessionDate').value!==baseline;
 function status(type,message){$('#status').className='connection-status '+type;$('#status').textContent=message;}
 function controls(){
  $('#planner').inert=busy||!access||!db;$('#setupButton').disabled=busy||!access;$('#subjectForm').inert=busy||!access;$('#councilCards').inert=needsReload;
  if(!db)return;const s=db.SEANCES_CM.find(s=>s.id===id),editable=!id||P.editable(db,id);
  $('#sessionDate').disabled=needsReload||!editable||!!s?.Date_confirmee;$('#saveSession').disabled=needsReload||!editable||!!s?.Date_confirmee;$('#confirmDate').disabled=needsReload||!editable||dirty();$('#newSession').disabled=needsReload;
 }
 async function fetchDB(){const results=await Promise.allSettled(P.tables.map(t=>grist.docApi.fetchTable(t)));const errors=results.flatMap((r,i)=>r.status==='rejected'?[P.tables[i]+': '+(r.reason?.message||r.reason)]:[]);if(errors.length)throw Error(errors.join(' ; '));if(!access)throw Error('Accès complet requis.');return Object.fromEntries(results.map((r,i)=>[P.tables[i],rows(r.value)]));}
 function renderCards(){
  $('#councilCards').innerHTML=db.SEANCES_CM.slice().sort((a,b)=>a.Date_heure_seance-b.Date_heure_seance).map(s=>{
   const subjects=db.SUJETS_PREVISIONNELS.filter(t=>t.Seance===s.id);
   return `<article class="card council-card ${s.id===id?'selected':''}"><div class="card-header"><div><span class="pill ${s.Date_confirmee?'confirmed':'forecast'}">${s.Date_confirmee?'Date confirmée':'Date provisoire'}</span><h3>${esc(s.Libelle_seance||P.localDate(s.Date_heure_seance))}</h3></div><button class="ghost-btn" data-council="${s.id}">Voir / modifier la date</button></div><button class="secondary-btn" data-subject-new="${s.id}" ${P.open(db,s.id)?'':'disabled'}>+ Sujet à prévoir</button><div class="council-items">${subjects.map(t=>`<div class="council-item"><div><span class="pill ${t.Deliberation?'draft':'forecast'}">${t.Deliberation?'Rédaction commencée':'À rédiger'}</span><button class="subject-link" data-subject-open="${t.id}">${esc(t.Intitule)}</button>${t.Note?`<p class="subject-note">${esc(t.Note)}</p>`:''}</div>${!t.Deliberation?`<button class="ghost-btn" data-subject-edit="${t.id}" ${P.open(db,s.id)?'':'disabled'}>Modifier / déplacer</button>`:''}</div>`).join('')||'<p class="hint">Aucun sujet prévu pour le moment.</p>'}</div></article>`;
  }).join('')||'<p class="hint">Aucun conseil programmé. Choisissez une date pour commencer.</p>';
 }
 function show(next){id=next;const s=db.SEANCES_CM.find(s=>s.id===id);$('#sessionHeading').textContent=s?'Date du conseil sélectionné':'Prévoir un conseil';$('#sessionDate').value=P.localDate(s?.Date_heure_seance);baseline=$('#sessionDate').value;$('#sessionState').textContent=s?(s.Date_confirmee?'Date confirmée.':'Date provisoire.'):'La date reste modifiable avant sa confirmation.';$('#confirmDate').hidden=!s;$('#confirmDate').textContent=s?.Date_confirmee?'Modifier la date confirmée':'Confirmer la date';renderCards();controls();}
 async function run(fn){if(busy)return;busy=true;controls();try{await fn();}catch(e){status('error',e.message);if($('#subjectDialog').open)$('#subjectError').textContent=e.message;}finally{busy=false;controls();}}
 function leave(){return !dirty()||confirm('Abandonner la modification de date non enregistrée ?');}
 function clean(){if(!dirty())return true;status('warning','Enregistrez la date avant de poursuivre.');return false;}
 async function save(build,after){if(needsReload||!access)return;await run(async()=>{const fresh=await fetchDB();if(JSON.stringify(fresh)!==JSON.stringify(db))throw Error('Les données ont changé. Actualisez avant d’enregistrer. Votre saisie est conservée.');const plan=build(fresh);if(!access)throw Error('Accès complet requis.');await grist.docApi.applyUserActions(plan.actions);id=plan.id;baseline=$('#sessionDate').value;needsReload=true;try{db=await fetchDB();needsReload=false;show(id);status('connected','✓ Enregistré dans Grist.');if(after)after();}catch(e){status('error','Enregistrement effectué. Actualisez pour recharger les données.');}});}
 async function refresh(){if(!leave())return;await run(async()=>{db=await fetchDB();needsReload=false;show(db.SEANCES_CM.some(s=>s.id===id)?id:0);status('connected','Connecté à Grist — planification des dates et des sujets.');});}
 $('#saveSession').onclick=()=>save(db=>P.schedulePlan(db,id,$('#sessionDate').value));$('#sessionDate').oninput=controls;$('#newSession').onclick=()=>{if(leave())show(0);};$('#refresh').onclick=refresh;
 $('#confirmDate').onclick=()=>{if(!clean())return;const confirmed=!!db.SEANCES_CM.find(s=>s.id===id).Date_confirmee;if(!confirmed||confirm('Repasser cette date en prévision ?'))save(db=>P.confirmDatePlan(db,id,!confirmed));};
 function subjectForm(sid,tid=0){if(!clean())return;subjectId=tid;const t=db.SUJETS_PREVISIONNELS.find(t=>t.id===tid);$('#subjectHeading').textContent=t?'Modifier le sujet':'Ajouter un sujet à prévoir';$('#subjectSession').innerHTML=db.SEANCES_CM.filter(s=>P.open(db,s.id)).map(s=>`<option value="${s.id}" ${s.id===(t?.Seance||sid)?'selected':''}>${esc(s.Libelle_seance)}</option>`).join('');$('#subjectTitle').value=t?.Intitule||'';$('#subjectNote').value=t?.Note||'';$('#subjectError').textContent='';$('#subjectDialog').showModal();}
 $('#closeSubject').onclick=()=>$('#subjectDialog').close();$('#subjectForm').onsubmit=e=>{e.preventDefault();save(db=>P.subjectPlan(db,subjectId,{session:Number($('#subjectSession').value),title:$('#subjectTitle').value,note:$('#subjectNote').value}),()=>$('#subjectDialog').close());};
 $('#councilCards').onclick=e=>{const b=e.target.closest('button');if(!b||b.disabled||needsReload)return;if(b.dataset.council&&leave()){show(Number(b.dataset.council));$('#sessionHeading').scrollIntoView({block:'center'});}if(b.dataset.subjectNew)subjectForm(Number(b.dataset.subjectNew));if(b.dataset.subjectEdit)subjectForm(0,Number(b.dataset.subjectEdit));if(b.dataset.subjectOpen&&clean())location.href='index.html?v=0.9.0&from=planning&subject='+Number(b.dataset.subjectOpen);};
 async function inspectSchema(){const results=await Promise.allSettled(['_grist_Tables','_grist_Tables_column'].map(t=>grist.docApi.fetchTable(t)));for(const r of results)if(r.status==='rejected')throw Error('Impossible de vérifier la structure Grist.');if(!access)throw Error('Accès complet requis.');return P.schemaPlan(rows(results[0].value),rows(results[1].value));}
 async function initialise(){await run(async()=>{const actions=await inspectSchema();if(actions.length){$('#setup').hidden=false;status('warning','Activez les sujets à prévoir.');return;}$('#setup').hidden=true;db=await fetchDB();show(0);status('connected','Connecté à Grist — planification des dates et des sujets.');});}
 $('#setupButton').onclick=()=>run(async()=>{const actions=await inspectSchema();if(actions.length)await grist.docApi.applyUserActions(actions);db=await fetchDB();$('#setup').hidden=true;show(0);status('connected','Planification activée.');});
 window.addEventListener('beforeunload',e=>{if(dirty()){e.preventDefault();e.returnValue='';}});
 if(!window.grist||parent===window){status('warning','Ouvrez cette page dans un widget Grist avec accès complet.');return;}
 grist.onOptions((o,i)=>{access=(i?.accessLevel??i?.access_level)==='full';controls();if(!access){status('warning','Accès complet au document requis.');return;}if(!db)initialise();});grist.ready({requiredAccess:'full'});
})();
