(function(){
 'use strict';const P=PlanningData,$=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 let subjectId=0,assignId=0;
 let db,id=0,desired=[],baseAgenda='',baseForm='',access=false,busy=false,needsReload=false;
 const fields=()=>({date:$('#sessionDate').value,place:$('#sessionPlace').value,convocation:$('#convocation').value,members:$('#members').value});
 const formDirty=()=>!!db&&JSON.stringify(fields())!==baseForm,agendaDirty=()=>JSON.stringify(desired)!==baseAgenda,dirty=()=>formDirty()||agendaDirty();
 const rows=t=>(t.id||[]).map((id,i)=>Object.fromEntries(Object.keys(t).map(k=>[k,t[k][i]])));
 function status(type,message){$('#status').className='connection-status '+type;$('#status').textContent=message;}
 async function fetchDB(){const result=await Promise.allSettled(P.tables.map(t=>grist.docApi.fetchTable(t)));const errors=result.flatMap((r,i)=>r.status==='rejected'?[P.tables[i]+': '+(r.reason?.message||r.reason)]:[]);if(errors.length)throw Error(errors.join(' ; '));if(!access)throw Error('Accès complet au document requis.');return Object.fromEntries(result.map((r,i)=>[P.tables[i],rows(r.value)]));}
 function controls(){
  $('#planner').inert=busy||!access||!db;$('#setupButton').disabled=busy||!access;$('#subjectForm').inert=busy||!access;$('#assignForm').inert=busy||!access;$('#councilCards').inert=needsReload;$('#unassignedDrafts').inert=needsReload;
  if(!db)return;const editable=!id||P.open(db,id);
  $('#sessionForm').disabled=!!(id&&!P.editable(db,id))||needsReload;$('#sessionDate').disabled=!!db.SEANCES_CM.find(s=>s.id===id)?.Date_confirmee;$('#confirmDate').disabled=needsReload||!P.editable(db,id)||dirty();$('#saveAgenda').disabled=!editable||needsReload||!agendaDirty();
  $('#toggleLock').disabled=needsReload||!P.editable(db,id)||dirty();
  $('#agendaHint').textContent=agendaDirty()?'● Modifications de l’ordre du jour non enregistrées.':P.open(db,id)?'Les flèches permettent de classer les points. Retirer un projet le conserve parmi les brouillons sans séance.':'Ordre du jour en lecture seule.';
  $('#agendaHint').classList.toggle('dirty',agendaDirty());
 }
 function renderAgenda(){
  if(!db)return;const open=id&&P.open(db,id)&&!needsReload,q=$('#search').value.toLocaleLowerCase('fr');
  const selected=new Set(desired.map(p=>p.Deliberation));
  const candidates=db.DELIBERATIONS.filter(d=>(!d.Seance||d.Seance===id)&&!selected.has(d.id)&&!db.ORDRE_DU_JOUR.some(p=>p.Deliberation===d.id)&&['','Brouillon service','Corrections demandées','Validé par la DGS','Inscrit à l’ordre du jour'].includes(d.Statut_deliberation||'')&&(d.Objet||'').toLocaleLowerCase('fr').includes(q));
  $('#available').innerHTML=candidates.map(d=>`<div class="project-row"><div><strong>${esc(d.Objet||'Sans objet')}</strong><small>${d.Seance===id?'Fléché vers cette séance':'Sans séance'} · ${esc(d.Statut_deliberation==='Brouillon service'?'Brouillon DGS':(d.Statut_deliberation||'Brouillon'))}</small></div><div class="project-tools"><button data-add="${d.id}" class="secondary-btn" ${open?'':'disabled'}>Ajouter à l’ordre du jour</button>${d.Seance===id?`<button data-unassign="${d.id}" class="ghost-btn" ${open?'':'disabled'}>Libérer</button>`:''}</div></div>`).join('')||'<p class="hint">Aucun projet disponible. Vous pouvez en créer dans le widget de rédaction.</p>';
  $('#agenda').innerHTML=desired.map((p,i)=>`<li class="project-row"><div><strong>${esc(db.DELIBERATIONS.find(d=>d.id===p.Deliberation)?.Objet||p.Intitule_point||'Point sans titre')}</strong><small>${p.Deliberation?'Délibération':esc(p.Type_point||'Information')}</small></div><div class="project-tools"><button class="ghost-btn" data-up="${i}" aria-label="Monter le point ${i+1}" ${open&&i>0?'':'disabled'}>↑</button><button class="ghost-btn" data-down="${i}" aria-label="Descendre le point ${i+1}" ${open&&i<desired.length-1?'':'disabled'}>↓</button>${p.Deliberation?`<button class="ghost-btn" data-remove="${i}" ${open?'':'disabled'}>Retirer</button>`:''}</div></li>`).join('')||'<p class="hint">Ajoutez les délibérations à examiner lors de ce conseil.</p>';
  $('#pointCount').textContent=desired.length+' point'+(desired.length>1?'s':'');controls();
 }
 function show(next){
  id=next;const s=db.SEANCES_CM.find(s=>s.id===id),params=db.PARAMETRES_APPLICATION[0]||{};
  $('#sessions').innerHTML='<option value="0">Nouvelle séance</option>'+db.SEANCES_CM.slice().sort((a,b)=>b.Date_heure_seance-a.Date_heure_seance).map(s=>`<option value="${s.id}">${esc(s.Libelle_seance||s.Reference_seance||'Séance '+s.id)}</option>`).join('');$('#sessions').value=String(id);
  $('#sessionDate').value=P.localDate(s?.Date_heure_seance);$('#sessionPlace').value=s?.Lieu_seance||params.Lieu_seance_defaut||'';$('#members').value=s?.Nb_membres_exercice||params.Nb_conseillers||db.ELUS.filter(e=>e.Actif).length||'';$('#convocation').value=s?.Date_convocation?new Date(s.Date_convocation*1000).toISOString().slice(0,10):'';
  $('#sessionHeading').textContent=s?'Conseil sélectionné':'Nouveau conseil prévisionnel';$('#confirmDate').hidden=!s;$('#confirmDate').textContent=s?.Date_confirmee?'Modifier la date confirmée':'Confirmer la date du conseil';$('#sessionState').textContent=s?(s.Date_confirmee?'● Date confirmée':'● Date provisoire'):'';$('#saveSession').textContent=s?'Enregistrer les informations':'Créer la séance';
  $('#agendaArea').hidden=!s;$('#toggleLock').hidden=!s;$('#toggleLock').textContent=s?.Ordre_du_jour_valide?'Rouvrir la préparation':'Verrouiller l’ordre du jour';$('#instructions').textContent=!s?'Créez une séance pour y affecter vos projets.':P.open(db,id)?'Ajoutez vos projets à l’ordre du jour puis classez-les. Les textes restent modifiables dans la rédaction tant que la préparation est ouverte.':'La préparation est verrouillée. Vous pouvez la rouvrir explicitement tant que le conseil n’a pas été envoyé aux élus ou commencé.';
  desired=structuredClone(P.points(db,id));baseAgenda=JSON.stringify(desired);baseForm=JSON.stringify(fields());renderAgenda();renderOverview();
 }
 function leave(){return !db||!dirty()||confirm('Abandonner les modifications non enregistrées ?');}
 async function run(fn){if(busy)return;busy=true;controls();try{return await fn();}catch(e){status('error',e.message);if($('#subjectDialog').open)$('#subjectError').textContent=e.message;if($('#assignDialog').open)$('#assignError').textContent=e.message;}finally{busy=false;controls();}}
 async function refresh(){if(!leave())return;await run(async()=>{db=await fetchDB();needsReload=false;show(db.SEANCES_CM.some(s=>s.id===id)?id:0);status('connected','Connecté à Grist — planification des conseils municipaux.');});}
 async function save(build,after){if(needsReload||!access)return;await run(async()=>{const fresh=await fetchDB();if(JSON.stringify(fresh)!==JSON.stringify(db))throw Error('Les données ont changé dans Grist. Actualisez avant d’enregistrer ; vos modifications restent à l’écran.');const plan=build(fresh);if(!access)throw Error('Accès complet requis.');if(plan.actions.length)await grist.docApi.applyUserActions(plan.actions);id=plan.id;needsReload=true;baseAgenda=JSON.stringify(desired);baseForm=JSON.stringify(fields());try{db=await fetchDB();needsReload=false;show(id);status('connected','✓ Enregistré dans Grist.');if(after)after(plan);}catch(e){status('error','Enregistrement effectué, mais relecture impossible. Cliquez sur Actualiser.');}});}
 $('#sessions').onchange=()=>{const next=Number($('#sessions').value);if(leave())show(next);else $('#sessions').value=String(id);};$('#newSession').onclick=()=>{if(leave())show(0);};$('#refresh').onclick=refresh;$('#search').oninput=renderAgenda;
 $('#saveSession').onclick=()=>{if(agendaDirty()){status('warning','Enregistrez d’abord les modifications de l’ordre du jour.');return;}save(db=>P.sessionPlan(db,id,fields()));};
 $('#saveAgenda').onclick=()=>{if(formDirty()){status('warning','Enregistrez d’abord les informations de la séance.');return;}save(db=>P.agendaPlan(db,id,desired));};
 $('#toggleLock').onclick=()=>{const lock=!db.SEANCES_CM.find(s=>s.id===id).Ordre_du_jour_valide;if(confirm(lock?'Verrouiller cet ordre du jour et la rédaction des projets associés ?':'Rouvrir la préparation et autoriser de nouveau la rédaction des projets associés ?'))save(db=>P.lockPlan(db,id,lock));};
 $('#sessionForm').oninput=controls;
 $('#agendaArea').onclick=e=>{
  const b=e.target.closest('button');if(!b||b.disabled||!P.open(db,id)||needsReload)return;
  if(b.dataset.add){desired.push({Deliberation:Number(b.dataset.add)});renderAgenda();}
  if(b.dataset.remove!==undefined){desired.splice(Number(b.dataset.remove),1);renderAgenda();}
  for(const [key,delta] of [['up',-1],['down',1]])if(b.dataset[key]!==undefined){const i=Number(b.dataset[key]);[desired[i],desired[i+delta]]=[desired[i+delta],desired[i]];renderAgenda();}
  if(b.dataset.unassign){if(dirty()){status('warning','Enregistrez les modifications en cours avant de libérer un projet.');return;}const did=Number(b.dataset.unassign);save(db=>{if(!P.open(db,id)||db.ORDRE_DU_JOUR.some(p=>p.Deliberation===did))throw Error('Ce projet ne peut plus être libéré.');return {id,actions:[['UpdateRecord','DELIBERATIONS',did,{Seance:0}],['AddRecord','JOURNAL_ACTIONS',null,{Date_action:Date.now()/1000,Seance:id,Deliberation:did,Utilisateur:0,Type_action:'Modification',Description:'Retrait du fléchage vers la séance',Niveau:'Information'}]]};});}
 };
 /* Additional scheduling and subjects UI. */
 function renderOverview(){
  const draftLabel=d=>db.ORDRE_DU_JOUR.some(p=>p.Deliberation===d.id)?'À l’ordre du jour':(['','Brouillon service','Corrections demandées'].includes(d.Statut_deliberation||'')?'En rédaction':d.Statut_deliberation);
  const draftRow=(d,free=false)=>`<div class="council-item"><div><span class="pill draft">${esc(draftLabel(d))}</span><strong>${esc(d.Objet||'Sans objet')}</strong></div><div class="project-tools"><button class="ghost-btn" data-draft="${d.id}">Ouvrir</button>${!db.ORDRE_DU_JOUR.some(p=>p.Deliberation===d.id)&&(!d.Seance||P.open(db,d.Seance))?`<button class="secondary-btn" data-assign="${d.id}">${free?'Affecter à un conseil':'Changer de séance'}</button>`:''}</div></div>`;
  $('#councilCards').innerHTML=db.SEANCES_CM.slice().sort((a,b)=>a.Date_heure_seance-b.Date_heure_seance).map(s=>{
   const pending=db.SUJETS_PREVISIONNELS.filter(t=>t.Seance===s.id&&!t.Deliberation),drafts=db.DELIBERATIONS.filter(d=>d.Seance===s.id),other=P.points(db,s.id).filter(p=>!p.Deliberation);
   return `<article class="card council-card ${id===s.id?'selected':''}"><div class="card-header"><div><span class="pill ${s.Date_confirmee?'confirmed':'forecast'}">${s.Date_confirmee?'Date confirmée':'Date provisoire'}</span><h3>${esc(s.Libelle_seance||P.localDate(s.Date_heure_seance)||'Conseil sans date')}</h3><p class="hint">${esc(s.Lieu_seance||'Lieu à préciser')} · ${pending.length} sujet(s) à rédiger · ${drafts.length} délibération(s)${s.Ordre_du_jour_valide?' · Ordre du jour verrouillé':''}</p></div><button class="secondary-btn" data-council="${s.id}">Préparer ce conseil</button></div><div class="project-tools"><button class="secondary-btn" data-subject-new="${s.id}" ${P.open(db,s.id)?'':'disabled'}>+ Sujet à prévoir</button><button class="secondary-btn" data-new-draft="${s.id}" ${P.open(db,s.id)?'':'disabled'}>+ Rédiger une délibération</button></div><div class="council-items">${pending.map(t=>`<div class="council-item"><div><span class="pill forecast">À rédiger</span><strong>${esc(t.Intitule)}</strong>${t.Note?`<p class="subject-note">${esc(t.Note)}</p>`:''}</div><div class="project-tools"><button class="ghost-btn" data-subject-edit="${t.id}" ${P.open(db,s.id)?'':'disabled'}>Modifier / déplacer</button><button class="secondary-btn" data-start-draft="${t.id}" ${P.open(db,s.id)?'':'disabled'}>Commencer la rédaction</button></div></div>`).join('')}${drafts.map(d=>draftRow(d)).join('')}${other.map(p=>`<div class="council-item"><strong>${esc(p.Intitule_point||p.Type_point)}</strong><span class="pill">Point sans délibération</span></div>`).join('')}${!pending.length&&!drafts.length&&!other.length?'<p class="hint">Aucun sujet ni délibération pour le moment.</p>':''}</div></article>`;
  }).join('')||'<p class="hint">Aucun conseil programmé. Utilisez la première partie pour en prévoir un.</p>';
  $('#unassignedDrafts').innerHTML=db.DELIBERATIONS.filter(d=>!d.Seance).map(d=>draftRow(d,true)).join('')||'<p class="hint">Aucune délibération sans séance.</p>';
 }
 function clean(){if(!dirty())return true;status('warning','Enregistrez ou abandonnez les modifications de la séance avant de poursuivre.');return false;}
 function navigateDraft(draft=0,session=0){if(!clean())return;location.href='index.html?v=0.8.0&from=planning'+(draft?'&draft='+draft:session?'&session='+session:'');}
 function sessionOptions(value,allowEmpty=false){return (allowEmpty?'<option value="0">Sans séance</option>':'')+db.SEANCES_CM.filter(s=>P.open(db,s.id)).sort((a,b)=>a.Date_heure_seance-b.Date_heure_seance).map(s=>`<option value="${s.id}" ${s.id===value?'selected':''}>${esc(s.Libelle_seance||P.localDate(s.Date_heure_seance))}${s.Date_confirmee?'':' — provisoire'}</option>`).join('');}
 function subjectForm(sid,tid=0){if(!clean())return;subjectId=tid;const subject=db.SUJETS_PREVISIONNELS.find(t=>t.id===tid);$('#subjectHeading').textContent=subject?'Modifier le sujet à prévoir':'Ajouter un sujet à prévoir';$('#subjectSession').innerHTML=sessionOptions(subject?.Seance||sid);$('#subjectTitle').value=subject?.Intitule||'';$('#subjectNote').value=subject?.Note||'';$('#subjectError').textContent='';$('#subjectDialog').showModal();$('#subjectTitle').focus();}
 $('#subjectForm').onsubmit=e=>{e.preventDefault();save(db=>P.subjectPlan(db,subjectId,{session:Number($('#subjectSession').value),title:$('#subjectTitle').value,note:$('#subjectNote').value}),()=>$('#subjectDialog').close());};
 $('#closeSubject').onclick=()=>$('#subjectDialog').close();$('#closeAssign').onclick=()=>$('#assignDialog').close();
 $('#assignForm').onsubmit=e=>{e.preventDefault();save(db=>P.assignPlan(db,assignId,Number($('#assignSession').value)),()=>$('#assignDialog').close());};
 $('#overview').addEventListener('click',e=>{
  const b=e.target.closest('button');if(!b||b.disabled||needsReload)return;
  if(b.dataset.council){if(leave()){show(Number(b.dataset.council));$('#sessionHeading').scrollIntoView({behavior:'smooth',block:'center'});}}
  if(b.dataset.subjectNew)subjectForm(Number(b.dataset.subjectNew));
  if(b.dataset.subjectEdit)subjectForm(0,Number(b.dataset.subjectEdit));
  if(b.dataset.startDraft&&clean())save(db=>P.startDraftPlan(db,Number(b.dataset.startDraft)),plan=>navigateDraft(plan.draftId));
  if(b.dataset.draft)navigateDraft(Number(b.dataset.draft));
  if(b.dataset.newDraft)navigateDraft(0,Number(b.dataset.newDraft));
  if(b.dataset.assign&&clean()){assignId=Number(b.dataset.assign);const d=db.DELIBERATIONS.find(d=>d.id===assignId);$('#assignTitle').textContent=d.Objet;$('#assignSession').innerHTML=sessionOptions(d.Seance||0,true);$('#assignSession').value=String(d.Seance||0);$('#assignError').textContent='';$('#assignDialog').showModal();}
 });
 $('#confirmDate').onclick=()=>{if(!clean())return;const confirmed=!!db.SEANCES_CM.find(s=>s.id===id).Date_confirmee;if(!confirmed||confirm('Repasser cette date en prévision pour pouvoir la modifier ?'))save(db=>P.confirmDatePlan(db,id,!confirmed));};
 async function inspectSchema(){const result=await Promise.allSettled(['_grist_Tables','_grist_Tables_column'].map(t=>grist.docApi.fetchTable(t)));for(const r of result)if(r.status==='rejected')throw Error('Impossible de vérifier la structure Grist : '+(r.reason?.message||r.reason));if(!access)throw Error('Accès complet requis.');return P.schemaPlan(rows(result[0].value),rows(result[1].value));}
 async function initialise(){await run(async()=>{const actions=await inspectSchema();if(actions.length){$('#setup').hidden=false;status('warning','Activez la nouvelle planification pour ajouter les sujets à prévoir.');return;}$('#setup').hidden=true;db=await fetchDB();needsReload=false;show(0);status('connected','Connecté à Grist — conseils programmés et sujets à prévoir.');});}
 $('#setupButton').onclick=()=>run(async()=>{const actions=await inspectSchema();if(actions.length)await grist.docApi.applyUserActions(actions);const remaining=await inspectSchema();if(remaining.length)throw Error('La structure n’a pas été entièrement créée. Réessayez l’activation.');db=await fetchDB();needsReload=false;$('#setup').hidden=true;show(0);status('connected','Nouvelle planification activée. Vos données existantes ont été conservées.');});

 window.addEventListener('beforeunload',e=>{if(db&&dirty()){e.preventDefault();e.returnValue='';}});
 if(!window.grist||parent===window){status('warning','Installez planning.html dans un widget Grist avec accès complet pour planifier vos conseils.');return;}
 grist.onOptions((o,i)=>{access=(i?.accessLevel??i?.access_level)==='full';controls();if(!access){status('warning','Autorisez l’accès complet au document.');return;}if(!db)initialise();});grist.ready({requiredAccess:'full'});
})();
